services:
  - type: web
    name: article_summarizer_agent
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "bash ./render-start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
