services:
  - type: web
    name: article_summarizer_agent
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
