services:
  - type: web
    name: article_summarizer_agent
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "bash ./render-start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: SKIP_DB_MIGRATIONS_ON_STARTUP
        value: "true"

  - type: worker
    name: article_summarizer_worker
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "celery -A celery_app worker --loglevel=info --concurrency=2"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
